CXXFLAGS = -O2 -Wall -std=c++17
THREAD = ${CXXFLAGS} -pthread

target=latest-beagle mrg2bgl vcf2g viewg subMat ljvcf pasteG g2dmu range unifrq

all:    ${target}

mv:
	mkdir -p ../bin
	mv ${target} ../bin
